presubmits:
  - name: pingcap-qe/ee-ops/prow_debug
    agent: jenkins
    always_run: false
    context: nest_prow_debug
    rerun_command: "/test nest_prow_debug"
    trigger: "((?m)^/test nest_prow_debug,?(\\s+|$))"
  - name: pull-test-dev-validate-labels-yaml
    decorate: true
    run_if_changed: "labels.yaml"
    branches:
      - ^master$
    spec:
      containers:
        - image: gcr.io/k8s-prow/label_sync:v20201204-d90be1ef6b
          command:
            - /app/label_sync/app.binary
          args:
            - --config=labels.yaml
            - --confirm=false
            - --only=tidb-community-bots/test-dev
            - --token=/etc/github/token
          volumeMounts:
            - name: github-token
              mountPath: /etc/github
              readOnly: true
      volumes:
        - name: github-token
          secret:
            secretName: github-token
  - name: hello
    decorate: true
    branches:
      - ^master$
    spec:
      containers:
        - image: debian
          command:
            - sh
            - -c
          args:
            - echo hello
  - name: yq-tekton
    always_run: true
    max_concurrency: 2
    decorate: false # need add this.
    agent: tekton-pipeline
    tekton_pipeline_run_spec:
      v1beta1:
        pipelineSpec:
          params:
            - name: JOB_SPEC
              type: string
            - name: PROW_JOB_ID
              type: string
          tasks:
            - name: yq-test
              taskRef:
                name: yq
              params:
                - name: SCRIPT
                  value: |
                    yq -n '.a = true'
                    yq -n '.PROW_JOB_ID = "$(params.PROW_JOB_ID)"'
                    yq -n '.PROW_JOB_ID = "$(params.JOB_SPEC)"'

