presubmits:
  - name: pull-configs-validate-labels-yaml
    decorate: true
    run_if_changed: 'labels.yaml'
    branches:
      - ^main$
    spec:
      containers:
        - image: gcr.io/k8s-prow/label_sync:v20201204-d90be1ef6b
          command:
            - /app/label_sync/app.binary
          args:
            - --config=labels.yaml
            - --confirm=false
            - --only=tidb-community-bots/test-dev
            - --token=/etc/github/token
          volumeMounts:
            - name: github-token
              mountPath: /etc/github
              readOnly: true
      volumes:
        - name: github-token
          secret:
            secretName: github-token